import keyMirror from 'keymirror';

export default keyMirror({
    LOAD_GROUPS_REQUEST: null,
    LOAD_GROUPS_SUCCESS: null,
    LOAD_GROUPS_FAIL: null,
    AUTHENTICATION_INITIALIZATION_REQUEST: null,
    AUTHENTICATION_INITIALIZATION_SUCCESS: null,
    AUTHENTICATION_INITIALIZATION_FAIL: null,
    AUTHENTICATION_AUTHORIZATION_REQUEST: null,
    AUTHENTICATION_AUTHORIZATION_SUCCESS: null,
    AUTHENTICATION_AUTHORIZATION_FAIL: null
})
